Update Working-Draft.md
isa-group/SLA4OAI-Specification pull request #25
Opened 2022-06-08 10:56 UTC by ignpelloz

2022-06-08 17:20 UTC, pjmolina requested changes
Asked for changes to use OAS instead of OAI for consistency with OpenAPI Spec

2022-06-08 17:20 UTC, pjmolina commented on versions/Working-Draft.md
> +sla4oai: 1.0.0
Use OAS instead of OAI for consistency.  `sla4oas`

2022-06-08 17:20 UTC, pjmolina commented on versions/Working-Draft.md
> +A **SLA4OAI** document is built as an extension to a given [OAS](https://github.com/OAI/OpenAPI-Specification) document. This extension will add an SLA definition to all or part of the services expos
SLA4OAI  rename to SLA4OAS- Fix in all places for consistency. 
Pablo to rename the repo also with forwarding.

2022-06-08 17:20 UTC, pjmolina commented on versions/Working-Draft.md
> +| 1.0.1   | 2022-06-08   | Updates.         |
Explain the list of updates, please.

2022-06-29 09:30 UTC, ignpelloz commented
Hi @pjmolina I have updated Working-Draft.md accordingly. I will open another PR to update the schema: sla4oai rename to sla4oas.

2022-07-06 17:28 UTC, pjmolina approved these changes
looks good. Tim and Pedro J.

2022-07-06 17:29 UTC, merged